name: CI

on: [push, pull_request]

jobs:
  check-syntax:
    name: Check syntax
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: fish-shop/install-fish-shell@v2
      - uses: fish-shop/syntax-check@v2

  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: fish-shop/install-fish-shell@v2
      - uses: fish-shop/indent-check@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: fish-shop/install-fish-shell@v2
      - uses: fish-shop/install-plugin@v2
        with:
          plugin-manager: fisher
          plugins: .
      - uses: fish-shop/run-fishtape-tests@v2
        with:
          patterns: tests/**.fish
